version: '3.8'

services:
  mcprag-remote:
    build:
      context: .
      dockerfile: Dockerfile.remote
    ports:
      - "8001:8001"
    environment:
      # Azure Search (read-only key)
      - ACS_ENDPOINT=${ACS_ENDPOINT}
      - ACS_QUERY_KEY=${ACS_QUERY_KEY:-${ACS_ADMIN_KEY}}
      - ACS_INDEX_NAME=${ACS_INDEX_NAME:-codebase-mcp-sota}
      
      # Stytch Authentication
      - STYTCH_PROJECT_ID=${STYTCH_PROJECT_ID}
      - STYTCH_SECRET=${STYTCH_SECRET}
      - STYTCH_ENV=${STYTCH_ENV:-test}
      
      # Redis
      - REDIS_URL=redis://redis:6379
      
      # Server Configuration
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
      - MCP_BASE_URL=${MCP_BASE_URL:-http://localhost:8001}
      - MCP_ALLOWED_ORIGINS=${MCP_ALLOWED_ORIGINS:-*}
      
      # User Tiers
      - MCP_ADMIN_EMAILS=${MCP_ADMIN_EMAILS}
      - MCP_DEVELOPER_DOMAINS=${MCP_DEVELOPER_DOMAINS}
      
      # Session
      - SESSION_DURATION_MINUTES=${SESSION_DURATION_MINUTES:-480}
      - MCP_REQUIRE_MFA=${MCP_REQUIRE_MFA:-true}
      
      # Logging
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      - MCP_DEBUG_TIMINGS=${MCP_DEBUG_TIMINGS:-false}
      
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mcprag-network
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
  
  mcprag-admin:
    build:
      context: .
      dockerfile: Dockerfile.remote
    ports:
      - "8002:8002"
    environment:
      # Azure Search (admin key for write operations)
      - ACS_ENDPOINT=${ACS_ENDPOINT}
      - ACS_ADMIN_KEY=${ACS_ADMIN_KEY}
      - ACS_INDEX_NAME=${ACS_INDEX_NAME:-codebase-mcp-sota}
      
      # Enable admin mode
      - MCP_ADMIN_MODE=true
      
      # Stytch
      - STYTCH_PROJECT_ID=${STYTCH_PROJECT_ID}
      - STYTCH_SECRET=${STYTCH_SECRET}
      - STYTCH_ENV=${STYTCH_ENV:-test}
      
      # Redis
      - REDIS_URL=redis://redis:6379
      
      # Server config
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8002
      - MCP_BASE_URL=${MCP_BASE_URL:-http://localhost:8001}
      
      # User Tiers
      - MCP_ADMIN_EMAILS=${MCP_ADMIN_EMAILS}
      - MCP_REQUIRE_MFA=true
      
      # Logging
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mcprag-network
    deploy:
      replicas: 1  # Single admin instance
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
  
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - mcprag-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
  
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - mcprag-remote
      - mcprag-admin
    restart: unless-stopped
    networks:
      - mcprag-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

volumes:
  redis-data:
    driver: local

networks:
  mcprag-network:
    driver: bridge