name = "claude-code-gateway"
main = "src/simple-worker.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Account and deployment settings
account_id = "a77e479f6736120eadd99973dbeb705e"
workers_dev = true
# route = { pattern = "claude.yourdomain.com/*", zone_name = "yourdomain.com" }

# Environment variables
[vars]
BRIDGE_URL = "http://localhost:8787/exec" # Your bridge via Cloudflare Tunnel
TURNSTILE_SECRET = "" # Optional: Cloudflare Turnstile for bot protection
ACCESS_JWT_SECRET = "" # Optional: For Cloudflare Access integration

# Durable Objects binding (commented out - not using DO in simple-worker)
# [[durable_objects.bindings]]
# name = "SESSION"
# class_name = "SessionDO"
# script_name = "claude-code-gateway"

# D1 Database for transcripts and metadata
[[d1_databases]]
binding = "DB"
database_name = "claude-code"
database_id = "f2cac7b3-8b37-49e6-b347-fdc130d07381"

# KV Namespace for user preferences (fast reads)
[[kv_namespaces]]
binding = "USER_PREFS"
id = "97d6ec11aeda46d69ced0b79a6d5cb3b"

# R2 Bucket for file attachments
[[r2_buckets]]
binding = "FILES"
bucket_name = "claude-code-files"

# Queue for background jobs
[[queues.producers]]
binding = "JOBS"
queue = "claude-code-jobs"

[[queues.consumers]]
queue = "claude-code-jobs"
max_batch_size = 10
max_batch_timeout = 30

# Development overrides
[env.development]
vars = { BRIDGE_URL = "http://localhost:8787/exec" }
upload_source_maps = true

# Production settings
[env.production]
# route = { pattern = "claude-api.yourdomain.com/*", zone_name = "yourdomain.com" }
logpush = true
upload_source_maps = true

# Assets configuration for serving static files
[assets]
directory = "./dist"

# Build configuration
[build]
command = "npm run build"
watch_paths = ["src/**/*.ts"]

# Local development settings
[dev]
ip = "localhost"
port = 8788
local_protocol = "http"

# Upload rules (exclude files)
[upload]
exclude = ["node_modules", ".git", "*.env", "*.log", "dist"]

# Observability settings
[observability]
enabled = true
head_sampling_rate = 1.0  # Log 100% of requests during development

# Migrations for D1 (commented out - not using DO)
# [[migrations]]
# tag = "v1"
# new_classes = ["SessionDO"]
# new_sqlite_databases = ["claude-code"]