name: "Enhanced GitHub Azure Integration"

on:
  push:
    paths:
      - "**/*.py"
      - "**/*.js"
      - "**/*.ts"

jobs:
  index-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py
            **/*.js
            **/*.ts

      - name: Index changed files locally
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ACS_ENDPOINT: ${{ secrets.ACS_ENDPOINT }}
          ACS_ADMIN_KEY: ${{ secrets.ACS_ADMIN_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          ACS_INDEX_NAME: ${{ vars.ACS_INDEX_NAME || 'codebase-mcp-sota' }}
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          python scripts/index_changed_files.py \
            --files "${{ steps.changed-files.outputs.all_changed_files }}" \
            --index-name "$ACS_INDEX_NAME"

      - name: Fallback index attempt
        if: failure()
        env:
          ACS_ENDPOINT: ${{ secrets.ACS_ENDPOINT }}
          ACS_ADMIN_KEY: ${{ secrets.ACS_ADMIN_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          ACS_INDEX_NAME: ${{ vars.ACS_INDEX_NAME || 'codebase-mcp-sota' }}
        run: |
          python scripts/index_changed_files.py \
            --files "${{ steps.changed-files.outputs.all_changed_files }}" \
            --index-name "$ACS_INDEX_NAME"
