name: Index Schema Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    name: Validate Azure Search Index Schema
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for prohibited files
      run: |
        # Fail if any of the removed creator scripts reappear
        prohibited_files=(
          "azure_search_enhanced.py"
          "index/create_index_3072.py"
          "scripts/create_index_with_skillset.py"
          "scripts/create_index_mcp_aligned.py"
          "scripts/create_index_from_json.py"
          "scripts/create_index_rest.py"
          "scripts/recreate_index_for_mcp.py"
        )
        
        found_prohibited=0
        for file in "${prohibited_files[@]}"; do
          if [ -f "$file" ]; then
            echo "❌ Prohibited file found: $file"
            found_prohibited=1
          fi
        done
        
        if [ $found_prohibited -eq 1 ]; then
          echo "⚠️ Prohibited index creator files found. Use index/create_enhanced_index.py instead."
          exit 1
        fi
        
        echo "✅ No prohibited files found"
    
    - name: Validate index schema
      env:
        ACS_ENDPOINT: ${{ secrets.ACS_ENDPOINT }}
        ACS_ADMIN_KEY: ${{ secrets.ACS_ADMIN_KEY }}
        ACS_INDEX_NAME: ${{ secrets.ACS_INDEX_NAME || 'codebase-mcp-sota' }}
      run: |
        if [ -z "$ACS_ENDPOINT" ] || [ -z "$ACS_ADMIN_KEY" ]; then
          echo "⚠️ Azure Search credentials not configured, skipping validation"
          exit 0
        fi
        
        python scripts/validate_index_canonical.py
    
    - name: Export schema for review
      if: always()
      env:
        ACS_ENDPOINT: ${{ secrets.ACS_ENDPOINT }}
        ACS_ADMIN_KEY: ${{ secrets.ACS_ADMIN_KEY }}
        ACS_INDEX_NAME: ${{ secrets.ACS_INDEX_NAME || 'codebase-mcp-sota' }}
      run: |
        if [ -z "$ACS_ENDPOINT" ] || [ -z "$ACS_ADMIN_KEY" ]; then
          echo "⚠️ Azure Search credentials not configured, skipping export"
          exit 0
        fi
        
        python scripts/check_index_schema_v2.py || true
        
        if [ -f "current_index_schema.json" ]; then
          echo "📋 Index schema exported to current_index_schema.json"
        fi
    
    - name: Upload schema artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: index-schema
        path: current_index_schema.json
        if-no-files-found: ignore

  check-canonical-path:
    runs-on: ubuntu-latest
    name: Check Canonical Creation Path
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Verify canonical creator exists
      run: |
        if [ ! -f "index/create_enhanced_index.py" ]; then
          echo "❌ Canonical index creator missing: index/create_enhanced_index.py"
          exit 1
        fi
        echo "✅ Canonical index creator found"
    
    - name: Verify validation scripts exist
      run: |
        required_scripts=(
          "scripts/validate_index_canonical.py"
          "scripts/check_index_schema.py"
          "scripts/check_index_schema_v2.py"
        )
        
        for script in "${required_scripts[@]}"; do
          if [ ! -f "$script" ]; then
            echo "❌ Required validation script missing: $script"
            exit 1
          fi
        done
        
        echo "✅ All validation scripts found"